[package]
name = "lss-index-lexical"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
camino.workspace = true
lss-types = { version = "0.1.0", path = "../types" }
serde.workspace = true
tantivy = "0.22.0"
thiserror.workspace = true

[lints]
workspace = true

[dev-dependencies]
tempfile.workspace = true
