[package]
name = "lss-extract"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
camino.workspace = true
lopdf = "0.34.0"
mime_guess = "2.0.5"
lss-config = { path = "../config" }
quick-xml = "0.37.2"
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "io-util"] }
tracing.workspace = true
zip = { version = "2.2.2", default-features = false, features = ["deflate"] }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
