[package]
name = "lss-crawl"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
camino.workspace = true
lss-config = { path = "../config" }
notify = "8.0.0"
notify-debouncer-full = "0.5.0"
rayon = "1"
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync", "time", "macros", "rt"] }
tracing.workspace = true
walkdir = "2.5.0"

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
