[package]
name = "lss-embed"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
huggingface_hub = { package = "hf-hub", version = "0.5.0" }
lss-config = { version = "0.1.0", path = "../config" }
ndarray = "0.17.2"
ort = { version = "2.0.0-rc.12", features = ["load-dynamic", "cuda"] }
serde_json.workspace = true
thiserror.workspace = true
tokenizers = "0.22.1"
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
